server:
  port: 8082
spring:
  application:
    name: user_invok
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka,http://localhost:10001/eureka
    registry-fetch-interval-seconds: 30
user-service:
  ribbon:
    NFLoadBalancerRuLeClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true