spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: 123456
  application:
    name: user_service
mybatis:
  type-aliases-package: edu.xatu.entity
server:
  port: 8081
logging:
  level:
    edu.xatu.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka,http://localhost:10000/eureka